### ISSUE TITLE
Add Ecommerce text classification dataset

### ISSUE THREAD

**Issue by SwarupKMondal** [Clueless-Community/Datasets#100]
I am a contributor at hacktoberfest2022. I want to work in this issue and add relevant dataset for ecommerce text classification which can be implemented using NLP. Add relevant label please.
Thank you

**Comment by nikhil25803** [comment]
Sure @SwarupKMondal | Add it and make a PR

**Comment by nikhil25803** [comment]
Closing this PR, as the PR has already been merged
