### ISSUE TITLE
Configure GitHub actions.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/Datasets#112]

**Comment by SatabrataPaul-GitAc** [comment]
Would like to work on it
Kindly assign it to me

**Comment by NeerajGartia21** [comment]
I would like to work on it.
Can you please assign it to me.

**Comment by NeerajGartia21** [comment]
@SatabrataPaul-GitAc are you working on it?

**Comment by NeerajGartia21** [comment]
@nikhil25803 can you assign it to me if @SatabrataPaul-GitAc isn't working.
