### ISSUE TITLE
Make an UI for this repository

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/Datasets#122]
We have an ample amount of collections now. So to make it accessible for the user, we want to make a dedicated website that represents this repository.

Please share a UI inspiration in the comment if you are willing to work on it. The best one will get assigned.

**Comment by durgeshm01722** [comment]
Hey Admins, I would surely love to build something like this for this platform. But, can you explain to me more clearly what exactly should be built? I mean, a portal where the users can just see the datasets available in this repo or a portal where users can add and edit the previously available data?

I would be happy to contribute. You can assign me this task.

**Comment by durgeshm01722** [comment]
Okay, got it. I can do it. Please assign it to me 👍

**Comment by nikhil25803** [comment]
Okay @durgeshm01722, assigning it to you. But upload a screenshot of the UI you build here before making a pull request.

**Comment by durgeshm01722** [comment]
Okay

**Comment by durgeshm01722** [comment]
Btw, the example website that you have give is a bit huge and complex. Is it okay if I make a simple one?

**Comment by nikhil25803** [comment]
@durgeshm01722 | It is just for reference, you can design it your way. Just keep it simple and accessible.

**Comment by durgeshm01722** [comment]
Okay, Thanks 👍

**Comment by durgeshm01722** [comment]
### Hey Admins!

I have completed my task 🙌

PR no. -  #217 

Here's the screenshot of the web application 👇

![Screenshot (518)](https://user-images.githubusercontent.com/85431456/196004877-836b32a7-cfe8-4f56-98bb-ed7bdaacaacb.png)
