### ISSUE TITLE
Add issues and PR templates relevant to this repositories.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/Datasets#131]

**Comment by shashankbhatgs** [comment]
can I work on this @nikhil25803 ?

**Comment by nikhil25803** [comment]
Sure @shashankbhatgs | Go ahead.
Make a contextual issue template, asking which dataset you are uploading and all. And in the PR template, make sure you add the checkbox, asking if have you cross-checked that the dataset you are uploading is not already included.
