### ISSUE TITLE
Configure GitHub actions to run create_datasets_md.py file on every merge.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/Datasets#132]
**Note**
+ A GitHub workflow name `python-app.yml` is created in the `.github/workflows`.
+ One just needs to configure it so that the `create_datasets_md.py` runs on ever merge.

**Comment by ahmedsilat44** [comment]
@nikhil25803 I saw the file and create_datasets_md.py is already there 
![image](https://user-images.githubusercontent.com/105588821/194845750-1f6c9bb1-dd8b-4417-9b06-1661de94a303.png)

**Comment by nikhil25803** [comment]
Hey @ahmedsilat44, I put it there, but it is not executing the result I want. On running the `create_dataset_md.py` should add/update all the datasets we have in the `DATASETS.md` file. But it is not happening.
