### ISSUE TITLE
Stress Detection Dataset

### ISSUE THREAD

**Issue by tandrimasingha** [Clueless-Community/Datasets#156]
### Description

Based on the human’s physical activity, the stress levels of the human being are detected and analyzed here. A dataset of 2001 samples is provided for human body humidity, body temperature and the number of steps taken by the user. Three different classifications of stress are performed, low stress, normal stress, and high stress.

**Comment by nikhil25803** [comment]
Great @tandrimasingha, add it and make a PR :)
