### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/Datasets#166]
### Description

+ Update `README.md`.
+ Add [NikhilRaj](https://github.com/nikhil25803) as a maintainer in the readme, as it is done in [this](https://github.com/Clueless-Community/web-ui-kit) one.

**Comment by rajnish254** [comment]
Hey @nikhil25803 , i can do this . please assign it to me.
Thanks

**Comment by nikhil25803** [comment]
Sure @rajnish254 , go ahead. :)

**Comment by rajnish254** [comment]
@nikhil25803 Created PR . Kindly check.

**Comment by rajnish254** [comment]
@nikhil25803 ,https://www.clueless.tech/profile/admin/86938309
