### ISSUE TITLE
[Add Dataset] Global Hunger Index Dataset

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/Datasets#207]
### Description

*@nikhil25803 I would like to add this dataset*

**Comment by nikhil25803** [comment]
Go ahead @ighoshsubho :)

**Comment by jyotika6221** [comment]
plz assign me this issue

**Comment by nikhil25803** [comment]
@jyotika6221, this issue has already been assigned. You may add any other unique Dataset.

**Comment by nikhil25803** [comment]
@ighoshsubho, have you added the data?
