### ISSUE TITLE
Idea of making a Data we always need!

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/Datasets#3]
While building applications we need data like School names, College names of India, and Tech Stack data.

Like we need medicine data to test out the app Medorant.

What about collecting all the data in this repo. So that everyone can get them easily whenever needed.

**Comment by sreehari2003** [comment]
> While building applications we need data like School names, College names of India, and Tech Stack data.
> 
> Like we need medicine data to test out the app Medorant.
> 
> What about collecting all the data in this repo. So that everyone can get them easily whenever needed.

## another way of doing this
if we want to get the all university or college names in india we could create a api by getting all the data from aicte website
https://facilities.aicte-india.org/dashboard/pages/angulardashboard.php#!/otherapprovals
we could use a webscrapper to add all the data. we even could limt the api request to third partys by pricing the api 👀.
i am really interested in this if you are building one do let me know✌️

@Rajdip019

**Comment by Rajdip019** [comment]
> > While building applications we need data like School names, College names of India, and Tech Stack data.
> > Like we need medicine data to test out the app Medorant.
> > What about collecting all the data in this repo. So that everyone can get them easily whenever needed.
> 
> ## another way of doing this
> if we want to get the all university or college names in india we could create a api by getting all the data from aicte website https://facilities.aicte-india.org/dashboard/pages/angulardashboard.php#!/otherapprovals we could use a webscrapper to add all the data. we even could limt the api request to third partys by pricing the api 👀. i am really interested in this if you are building one do let me know✌️
> 
> @Rajdip019

Yes, we are building this API using FAST API and @nikhil25803 is on it already. You can help us if you want, you are more than welcome to help.🙌
