### ISSUE TITLE
[Add Dataset] 10.000 Chess Games with Centipawn Loss

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/Datasets#314]
### Description

Can Data Prove Cheating in Chess?

### Screenshots

![image](https://user-images.githubusercontent.com/77881638/197424356-7a4e9908-82ed-49d0-8a55-0a54d1aee593.png)

**Comment by nik132-eng** [comment]
please assign me this issue for hacktoberfest

**Comment by nikhil25803** [comment]
Go ahead @nik132-eng :)

**Comment by nikhil25803** [comment]
Hey @nik132-eng | Add the PR by today evening because all the issues will be closed by tonight :))
