### ISSUE TITLE
[Add Dataset]Bitcoin News Article Corpora

### ISSUE THREAD

**Issue by Nupoor10** [Clueless-Community/Datasets#343]
### Description

This dataset contains the corpora of news articles about Bitcoin extracted using Newscatcher API which can be used for Natural Language Processing.

**Comment by nikhil25803** [comment]
Sure @Nupoor10, add it and make a PR.

**Comment by Nupoor10** [comment]
Hii I have already created a PR for the same : #346

**Comment by Nupoor10** [comment]
If there are any changes to be made plz inform and I will do so accordingly

**Comment by nikhil25803** [comment]
Sorry I didn't notice :`) 
Thanks for contributing though 🫂
