### ISSUE TITLE
Add another ecommerce dataset

### ISSUE THREAD

**Issue by neelshah2409** [Clueless-Community/Datasets#45]

**Comment by Rajdip019** [comment]
Can you share a bit more about the data you are planing to add. @neelshah2409

**Comment by neelshah2409** [comment]
> Can you share a bit more about the data you are planing to add. @neelshah2409

I have the dataset for understanding the product sale of flipkart.

**Comment by Rajdip019** [comment]
You can add it here. sure @neelshah2409
