### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Datasets#6]
Creating a better documentation which explains the dataset well and linking the dataset with the title

**Comment by itzROHIT-coder** [comment]
Well, I can do this @nikhil25803. Assign this to me.

**Comment by nikhil25803** [comment]
Okay @itzROHIT-coder, go ahead. Make a `Datasets.md` file and mention all the datasets avaliable along with the link.

**Comment by vijay2249** [comment]
@nikhil25803 I created a new pr #53 for automating this task.
@itzROHIT-coder do checkout this PR for any missing cases that I missed them unfortunately.
