### ISSUE TITLE
Populate the following with more data

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Datasets#8]
- [Cities](https://github.com/Clueless-Community/Datasets/blob/main/Data/countries_cities/countries_city.json)

**Comment by Rajdip019** [comment]
@Roshaen Check this for cities [https://simplemaps.com/data/world-cities](Here)

**Comment by dishant-yadav** [comment]
What exactly do I need to do for this issue? @Rajdip019 
Do I need to more cities to the list?

**Comment by Rajdip019** [comment]
Yes form authentic source. @dishant-yadav

**Comment by dishant-yadav** [comment]
Okay

**Comment by SahilSingh177** [comment]
Please assign me this issue.

**Comment by AK-codingmaniac** [comment]
@Rajdip019 We just have to add the name of cities,right?
where can we get the source?

**Comment by Rajdip019** [comment]
You can search on the internet and get as much as filtered data. @AK-codingmaniac

**Comment by AK-codingmaniac** [comment]
So I don't have to provide the source right?

**Comment by AK-codingmaniac** [comment]
@Rajdip019 I have added a city which was not there in the list before
Please see to it and if it is correct,please merge it as soon as possible for HacktoberFest 2022

**Comment by AK-codingmaniac** [comment]
If it is correct,I will add more cities to the list

**Comment by AK-codingmaniac** [comment]
Now check @Rajdip019 PR no. #47 
If it is correct then please merge it as soon as possible for HacktoberFest 2022

**Comment by chakradhar4** [comment]
@Rajdip019 can i add more to the list ?

**Comment by hritikbhattacharya** [comment]
@Rajdip019 I want to add some dataset related to Wikipedia edits ..almost 1000 edits details i have added to the dataset.. if it is a valid dataset for the repo allow me to add it
