### ISSUE TITLE
Add Dataset for Games for Machine Learning

### ISSUE THREAD

**Issue by MihirRajeshPanchal** [Clueless-Community/Datasets#88]
Gaming industry in future is expanding. Machine Learning algorithms for gaming will be useful. Open Source Dataset repository will be helpful

**Comment by MihirRajeshPanchal** [comment]
Please Assign me this

**Comment by MihirRajeshPanchal** [comment]
@nikhil25803 please assign me this task

**Comment by nikhil25803** [comment]
Sure @MihirRajeshPanchal | Go ahead

**Comment by MihirRajeshPanchal** [comment]
@nikhil25803 I have generated a PR please review it and suggest any changes

**Comment by nikhil25803** [comment]
Closing this issue as the PR has been merged. Thanks @MihirRajeshPanchal :)
