### ISSUE TITLE
Add dataset of Infant Mortality Rate estimated 2020

### ISSUE THREAD

**Issue by prakrit55** [Clueless-Community/Datasets#89]
I will be adding dataset of infant mortality rate as estimated in 2020. If this is reviewed and accepted please assign me.

**Comment by nikhil25803** [comment]
Sure @prakrit55 , Go ahead.

**Comment by prakrit55** [comment]
Hey @nikhil25803 , previously I made a pr I think that was not accepted So I made a new one and this is different and improved one.
